In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
train=pd.read_csv('/kaggle/input/competitions/digit-recognizer/train.csv')
test=pd.read_csv('/kaggle/input/competitions/digit-recognizer/test.csv')
print(train.shape)
print(test.shape)

(42000, 785)
(28000, 784)

In [2]:
train.head()

,label,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [3]:
X=train.drop('label',axis=1)
y=train['label']

In [4]:
X=X/255.0
test=test/255.0

In [5]:
X.shape

(42000, 784)

In [6]:
from sklearn.model_selection import train_test_split
X_train,X_valid,y_train,y_valid=train_test_split(X,y,test_size=0.2,random_state=42)

In [7]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
model=Sequential()

2026-06-15 02:41:48.293631: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1781491308.684530      58 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1781491308.792591      58 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1781491309.771906      58 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1781491309.771933      58 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1781491309.771936      58 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1781491309.771938      58 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.

In [8]:
model.add(Dense(128,activation='relu',input_shape=(784,)))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
I0000 00:00:1781491328.151012      58 gpu_device.cc:2019] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 13757 MB memory:  -> device: 0, name: Tesla T4, pci bus id: 0000:00:04.0, compute capability: 7.5
I0000 00:00:1781491328.156848      58 gpu_device.cc:2019] Created device /job:localhost/replica:0/task:0/device:GPU:1 with 13757 MB memory:  -> device: 1, name: Tesla T4, pci bus id: 0000:00:05.0, compute capability: 7.5

In [9]:
model.add(Dense(64,activation='relu'))

In [10]:
model.add(Dense(10,activation='softmax'))

In [11]:
model.compile(optimizer='adam',loss='sparse_categorical_crossentropy',metrics=['accuracy'])

In [12]:
histroy=model.fit(X_train,y_train,epochs=10,validation_data=[X_valid,y_valid])

Epoch 1/10

WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1781491331.274076     130 service.cc:152] XLA service 0x79b19801f310 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
I0000 00:00:1781491331.274121     130 service.cc:160]   StreamExecutor device (0): Tesla T4, Compute Capability 7.5
I0000 00:00:1781491331.274125     130 service.cc:160]   StreamExecutor device (1): Tesla T4, Compute Capability 7.5
I0000 00:00:1781491331.616895     130 cuda_dnn.cc:529] Loaded cuDNN version 91002

  71/1050 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.4759 - loss: 1.7115

I0000 00:00:1781491332.726591     130 device_compiler.h:188] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.

1050/1050 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - accuracy: 0.9119 - loss: 0.3074 - val_accuracy: 0.9501 - val_loss: 0.1655
Epoch 2/10
1050/1050 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9629 - loss: 0.1238 - val_accuracy: 0.9624 - val_loss: 0.1282
Epoch 3/10
1050/1050 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9736 - loss: 0.0861 - val_accuracy: 0.9612 - val_loss: 0.1199
Epoch 4/10
1050/1050 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9806 - loss: 0.0619 - val_accuracy: 0.9718 - val_loss: 0.0965
Epoch 5/10
1050/1050 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9852 - loss: 0.0471 - val_accuracy: 0.9606 - val_loss: 0.1324
Epoch 6/10
1050/1050 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9870 - loss: 0.0385 - val_accuracy: 0.9631 - val_loss: 0.1304
Epoch 7/10
1050/1050 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9899 - loss: 0.0304 - val_accuracy: 0.9717 - val_loss: 0.1062
Epoch 8/10
1050/1050 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9909 - loss: 0.0269 - val_accuracy: 0.9724 - val_loss: 0.1074
Epoch 9/10
1050/1050 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9934 - loss: 0.0200 - val_accuracy: 0.9695 - val_loss: 0.1268
Epoch 10/10
1050/1050 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9935 - loss: 0.0196 - val_accuracy: 0.9707 - val_loss: 0.1212

In [13]:
loss,accuracy=model.evaluate(X_valid,y_valid)
print(accuracy)

263/263 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9707 - loss: 0.1212
0.970714271068573

In [14]:
pred=model.predict(test)

875/875 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step

In [15]:
pred = np.argmax(
    pred,
    axis=1
)

In [18]:
submission = pd.DataFrame({
    'ImageId': range(1, len(pred)+1),
    'Label': pred
})

In [19]:
submission.head()

   ImageId  Label
0        1      2
1        2      0
2        3      9
3        4      9
4        5      3

In [29]:
submission.to_csv(
    'submission.csv',
    index=False
)

In [28]:
!ls

submission1.csv  submission.csv